"""empty message

Revision ID: 514b5e9fbcff
Revises: 09f948278962
Create Date: 2025-05-06 14:50:00.766068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514b5e9fbcff'
down_revision = '09f948278962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_product_unique', ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_user', schema=None) as batch_op:
        batch_op.drop_constraint('user_product_unique', type_='unique')

    # ### end Alembic commands ###
